apiVersion: v1
kind: Secret
metadata:
  name: portfolio-secret
  namespace: default
type: Opaque
stringData:
  ADMIN_PASSWORD_HASH: "$$2a$$12$$MYMdK40vVLesykNo5mV3quOIMAaAGOqjZpjyUzRDS5RkcbGsR0Kjq"
  JWT_SECRET: "d8922a597209eb10271ff4622cc90ba01f071b2bc55d4f02d57cd5a925e1886043626206db821dcc53db4dd050ed833c"
